### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by karissa** [debtcollective/aaa#1]
- [x] donation page
- [x] hit 'next' on join
- [x] 'what happens when I join?' scroller
- [x] mobile nav
- [x] general social media sharing buttons at footer
- [ ] card sharing
- [ ] click link and scroll bar
